airbyte_dbt_test:
  outputs:
    dev:
      account: xy84596.ap-south-1
      database: AIRBYTE_DATABASE
      password: password
      role: AIRBYTE_ROLE
      schema: AIRBYTE_SCHEMA
      threads: 200
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
